export const POSTS_RECEIVED = "POSTS_RECEIVED";
export const POST_CREATED = "POSTS_CREATED";
export const POST_UPDATED = "POST_UPDATED";
export const POST_DELETED = "POST_DELETED";
export const POST_LIKED = "POST_LIKED";
export const POST_UNLIKED = "POST_UNLIKED";

export const COMMENTS_RECEIVED = "COMMENTS_RECEIVED";
export const COMMENT_CREATED = "COMMENTS_CREATED";
export const COMMENT_UPDATED = "COMMENTS_UPDATED";
export const COMMENT_DELETED = "COMMENTS_DELETED";
export const COMMENT_LIKED = "COMMENT_LIKED";
export const COMMENT_UNLIKED = "COMMENT_UNLIKED";

export const TOPICS_RECEIVED = "TOPICS_RECEIVED";
export const AUTHORS_RECEIVED = "AUTHORS_RECEIVED";
export const AUTHOR_UPDATED = "AUTHOR_UPDATED";
